apiVersion: v1
kind: Service
metadata:
  name: student-management-service
  namespace: devops
spec:
  selector:
    app: student-management
  ports:
    - protocol: TCP
      port: 8080      # Port externe (celui que tu utiliseras)
      targetPort: 8089 # Port interne (celui de ton code Java)
      nodePort: 30001
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-management
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-management
  template:
    metadata:
      labels:
        app: student-management
    spec:
      containers:
      - name: student-management
        image: student-management-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8089 # <--- DOIT ÊTRE 8089 pour correspondre au code
