apiVersion: v1
kind: Service
metadata:
  name: student-management-service
  namespace: devops
spec:
  type: NodePort
  selector:
    app: student-management
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8089
      nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-management
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-management
  template:
    metadata:
      labels:
        app: student-management
    spec:
      containers:
      - name: student-management
        image: student-management-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8089
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql:3306/student_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "root"
